### ISSUE TITLE
Greetings ...

### ISSUE THREAD

**Issue by jacksonbrumbaugh** [RyanSaxe/mtg#9]
Sorry to reach out this way ...

Thought it might be different enough to catch ur eye w/o being _too_ annoying

i @-d u over on Twitter with an idea for a neural net / ML project that i think could help me at work

& ur MTG draft helper came to mind!

I was a huge fan listening to some podcasts in which u detailed building / testing this algorithm

so I figured ... Why not shoot my shot trying to contact u 😅

hope ur having a fantastic Tuesday!

> Jackson

**Comment by RyanSaxe** [comment]
Hi @jacksonbrumbaugh 

I wasn't really checking this, but I am relatively active on Twitter and Discord. You're welcome to message me there again if this is still relevant.
